version: "3"

services:
  mongo:
    image: huynhquangtoan/mongo-health-http:latest
    environment:
      MONGODB_URI: mongodb://localhost:27017
    ports:
      - "8080:3000"
    restart: unless-stopped
